---

_version_control_gh_apt_repo_name: github-cli
_version_control_gh_apt_repo_url: https://cli.github.com/packages/
_version_control_gh_apt_repo_suites: stable
_version_control_gh_apt_repo_components:
  - main
_version_control_gh_apt_repo_signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
