---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update package manager cache (Linux)
      become: yes
      ansible.builtin.package:
        update_cache: yes
      when:
        - ansible_system == 'Linux'

  roles:
    - role: warpcode.development_computer.php
