---
- name: Converge
  hosts: all
  roles:
    - role: warpcode.development_computer.build_tools
    - role: warpcode.development_computer.encryption
    - role: warpcode.development_computer.php
    - role: warpcode.development_computer.python
    - role: warpcode.development_computer.version_control
    - role: warpcode.development_computer.neovim
