---
- name: Include OS-specific variables
  include_vars: "{{ ansible_system }}.yml"

- name: Install (Linux)
  become: true
  ansible.builtin.package:
    name: "{{ _php_packages }}"
  when:
    - ansible_system == "Linux"

- name: Install (MacOs)
  community.general.homebrew:
    name: "{{ _php_packages }}"
  when:
    - ansible_system == "Darwin"

- name: Install (Windows)
  become: true
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ _php_packages }}"
  when:
    - ansible_system == "Win32NT"
