---
- name: Include OS-specific variables
  ignore_errors: true
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}/main.yml"
    - "{{ ansible_system }}.yml"
  loop_control:
    loop_var: item

- name: Install (Linux)
  become: true
  ansible.builtin.package:
    name: "{{ _build_tools_packages }}"
  when:
    - ansible_system == "Linux"
